--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2023-02-08 16:49:26

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16434)
-- Name: arrangements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.arrangements (
    id integer NOT NULL,
    name text NOT NULL,
    vessel_type text DEFAULT ''::text NOT NULL,
    vessel_count integer DEFAULT 0 NOT NULL,
    foam_count integer DEFAULT 0 NOT NULL,
    card_holder boolean DEFAULT false NOT NULL,
    venmo boolean DEFAULT false NOT NULL,
    paypal boolean DEFAULT false NOT NULL,
    done boolean DEFAULT false NOT NULL,
    json json
);


ALTER TABLE public.arrangements OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16448)
-- Name: arrangements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.arrangements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arrangements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16423)
-- Name: flowers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.flowers (
    id integer NOT NULL,
    name text NOT NULL,
    price_per_stem double precision DEFAULT 0.00 NOT NULL
);


ALTER TABLE public.flowers OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16430)
-- Name: flowers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.flowers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flowers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3191 (class 2606 OID 16447)
-- Name: arrangements arrangements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arrangements
    ADD CONSTRAINT arrangements_pkey PRIMARY KEY (id);


--
-- TOC entry 3187 (class 2606 OID 16429)
-- Name: flowers flowers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flowers
    ADD CONSTRAINT flowers_pkey PRIMARY KEY (id);


--
-- TOC entry 3193 (class 2606 OID 16450)
-- Name: arrangements name_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arrangements
    ADD CONSTRAINT name_unique UNIQUE (name);


--
-- TOC entry 3189 (class 2606 OID 16433)
-- Name: flowers unique_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flowers
    ADD CONSTRAINT unique_name UNIQUE (name);


-- Completed on 2023-02-08 16:49:26

--
-- PostgreSQL database dump complete
--

