--
-- PostgreSQL database dump
--
 -- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1
 -- Started on 2023-02-10 13:34:10

SET statement_timeout = 0;


SET lock_timeout = 0;


SET idle_in_transaction_session_timeout = 0;


SET client_encoding = 'UTF8';


SET standard_conforming_strings = on;


SELECT pg_catalog.set_config('search_path', '', false);


SET check_function_bodies = false;


SET xmloption = content;


SET client_min_messages = warning;


SET row_security = off;


SET default_tablespace = '';


SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 16512)
-- Name: arrangements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.arrangements ( id integer NOT NULL,
                                              name text NOT NULL,
                                                        vessel_type text DEFAULT ''::text NOT NULL,
                                                                                          vessel_count integer DEFAULT 0 NOT NULL,
                                                                                                                         foam_count integer DEFAULT 0 NOT NULL,
                                                                                                                                                      card_holder boolean DEFAULT false NOT NULL,
                                                                                                                                                                                        venmo boolean DEFAULT false NOT NULL,
                                                                                                                                                                                                                    paypal boolean DEFAULT false NOT NULL,
                                                                                                                                                                                                                                                 done boolean DEFAULT false NOT NULL,
                                                                                                                                                                                                                                                                            vessel_price double precision DEFAULT 0,
                                                                                                                                                                                                                                                                                                                  json text DEFAULT ''::text NOT NULL);


ALTER TABLE public.arrangements OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16565)
-- Name: arrangements_flowers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.arrangements_flowers ( flower_id integer NOT NULL,
                                                             arrangement_id integer NOT NULL,
                                                                                    count integer DEFAULT 1 NOT NULL,
                                                                                                            category text DEFAULT ''::text NOT NULL);


ALTER TABLE public.arrangements_flowers OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16524)
-- Name: arrangements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.arrangements
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
    ( SEQUENCE NAME public.arrangements_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

--
-- TOC entry 216 (class 1259 OID 16525)
-- Name: flowers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.flowers ( id integer NOT NULL,
                                         name text NOT NULL,
                                                   price_per_bundle double precision DEFAULT 0 NOT NULL,
                                                                                               stem_count integer DEFAULT 1 NOT NULL,
                                                                                                                            price_per_stem double precision GENERATED ALWAYS AS ((price_per_bundle / (stem_count)::double precision)) STORED);


ALTER TABLE public.flowers OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16531)
-- Name: flowers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.flowers
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
    ( SEQUENCE NAME public.flowers_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

--
-- TOC entry 218 (class 1259 OID 16538)
-- Name: hard_goods; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hard_goods ( id integer NOT NULL,
                                            arrangement_id integer NOT NULL,
                                                                   name text NOT NULL,
                                                                             price double precision DEFAULT 0 NOT NULL);


ALTER TABLE public.hard_goods OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16544)
-- Name: hard_goods_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hard_goods
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
    ( SEQUENCE NAME public.hard_goods_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

--
-- TOC entry 220 (class 1259 OID 16545)
-- Name: multipliers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.multipliers ( name text NOT NULL,
                                            value double precision DEFAULT 0 NOT NULL);


ALTER TABLE public.multipliers OWNER TO postgres;

--
-- TOC entry 3212 (class 2606 OID 16552)
-- Name: arrangements arrangements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arrangements ADD CONSTRAINT arrangements_pkey PRIMARY KEY (id);

--
-- TOC entry 3214 (class 2606 OID 16554)
-- Name: arrangements arrangements_unique_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arrangements ADD CONSTRAINT arrangements_unique_name UNIQUE (name);

--
-- TOC entry 3216 (class 2606 OID 16556)
-- Name: flowers flowers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flowers ADD CONSTRAINT flowers_pkey PRIMARY KEY (id);

--
-- TOC entry 3218 (class 2606 OID 16558)
-- Name: flowers flowers_unique_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flowers ADD CONSTRAINT flowers_unique_name UNIQUE (name);

--
-- TOC entry 3220 (class 2606 OID 16560)
-- Name: hard_goods hard_goods_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hard_goods ADD CONSTRAINT hard_goods_pkey PRIMARY KEY (id);

--
-- TOC entry 3224 (class 2606 OID 16564)
-- Name: multipliers multipliers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multipliers ADD CONSTRAINT multipliers_pkey PRIMARY KEY (name);

--
-- TOC entry 3225 (class 1259 OID 16590)
-- Name: fki_arrangements_hard_goods_arrangement_id_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_hard_goods_arrangement_id_fkey ON public.hard_goods USING btree (arrangement_id);

--
-- TOC entry 3227 (class 2606 OID 16573)
-- Name: arrangements_flowers arrangements_flowers_arrangement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arrangements_flowers ADD CONSTRAINT arrangements_flowers_arrangement_id_fkey
FOREIGN KEY (arrangement_id) REFERENCES public.arrangements(id);

--
-- TOC entry 3228 (class 2606 OID 16568)
-- Name: arrangements_flowers arrangements_flowers_flower_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arrangements_flowers ADD CONSTRAINT arrangements_flowers_flower_id_fkey
FOREIGN KEY (flower_id) REFERENCES public.flowers(id);

--
-- TOC entry 3229 (class 2606 OID 16585)
-- Name: arrangements_hard_goods arrangements_hard_goods_arrangement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hard_goods ADD CONSTRAINT hard_goods_arrangement_id_fkey
FOREIGN KEY (arrangement_id) REFERENCES public.arrangements(id);

-- Completed on 2023-02-10 13:34:10
 --
-- PostgreSQL database dump complete
--
